linters-settings:
  funlen:
    lines: 60
    statements: 40

  goheader:
    template-path: .goheader.template

  lll:
    line-length: 100
    tab-width: 4

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - exhaustive
    - funlen
    - goconst
    - goheader
    - goimports
    - gomnd
    - gosec
    - importas
    - lll
    - misspell
    - nestif
    - prealloc
    - tagliatelle
    - revive
    - dupl
    - makezero
    - stylecheck
    - unused
  fast: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - gosec
