name: "ci"

on:
  push:
  pull_request:
    branches: main
  schedule:
    # Run at 5:21 am every Thursday morning.
    - cron: '21 5 * * 4'

jobs:
  ci:
    runs-on: ubuntu-latest
    # permissions:
    #  contents: write # Needed to update the coverage badge.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Needed to update coverage badge and to run goreleaser.
        fetch-depth: 0

    - name: Install Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: |
        sudo apt-get install make

    - name: Set up project
      run: make setup

    - name: Lint project, core part
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: core
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        # Optional: if set to true then the action will use pre-installed Go.
        skip-go-installation: true

    - name: Lint project, cli part
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: cli
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        # Optional: if set to true then the action will use pre-installed Go.
        skip-go-installation: true

    # TODO: uncomment once tests have been added
    # - name: Test project and generate test coverage
    #   run: |
    #    make test
    #    make readme_test
    #    make coverage_badge_report.out
    #
    # - name: Generate coverage badge
    #   uses: tj-actions/coverage-badge-go@v1
    #   with:
    #     filename: coverage_badge_report.out
    #
    # - name: Push changes if on main branch
    #   if: steps.readme_check.outputs.README_CHANGED == '1' && github.ref == 'refs/heads/main'
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ github.token }}
    #     branch: ${{ github.head_ref }}

    - name: Release binaries on tag
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        args: release --rm-dist
        workdir: ./cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
