name: "ci"

on:
  push:
  pull_request:
    branches: main

# Ensure there is only ever one workflow of this kind running at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  ci:
    runs-on: ubuntu-latest
    # Avoid very long running jobs.
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Needed to update coverage badge and to run goreleaser.
          fetch-depth: 0

      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          # System.
          sudo apt-get install make wget curl
          # Go.
          curl -sSfL "${RAW_URL}/${LINT}" | sudo sh -s -- -b "${TARGET}" v1.64.4
          # Custom.
          sudo wget -O "${TARGET}/mdslw" "${MDSLW_URL}/${MDSLW_BIN}"
          sudo chmod +x "${TARGET}/mdslw"
        env:
          RAW_URL: https://raw.githubusercontent.com
          LINT: golangci/golangci-lint/master/install.sh
          MDSLW_URL: https://github.com/razziel89/mdslw/releases/latest/download/
          MDSLW_BIN: mdslw_x86_64-unknown-linux-musl
          TARGET: /usr/local/bin

      - name: Set up project
        run: make setup

      - name: Build binary
        run: make build

      - name: Lint project
        run: make lint

      - name: Build all release binaries on main
        uses: goreleaser/goreleaser-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          # The snapshot flag is needed since we do not want to require a tag just
          # for building this.
          args: build --clean --snapshot
          workdir: ./cli
        env:
          # When running in this mode, goreleaser requires the cli version to be
          # provided via an env var.
          CLIVERSION: ci-cd

      - name: Set CLIVERSION env var on tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo >> $GITHUB_ENV "CLIVERSION=$(
            git describe --exact-match --tags | sed 's/^v//'
          )"

      - name: Release binaries on tag
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          args: release --clean
          workdir: ./cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test core module and generate test coverage
        working-directory: ./core/
        run: |
          make test
          make coverage_badge_report.out

      - name: Test CLI module and generate test coverage
        working-directory: ./cli/
        run: |
          make test
          make coverage_badge_report.out

      - name: Generate CLI module coverage badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: ./cli/coverage_badge_report.out
          text: CLI_Coverage

      - name: Generate core module coverage badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: ./core/coverage_badge_report.out
          text: Core_Coverage

      - name: Update readme in repo
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          # If any of the following commands fail, it means the readme did not
          # change. Ignore such errors.
          git add README.md &&
          git commit -m "Auto-update coverage badges [skip ci] [ci skip]" &&
          git push origin main || :

  docker-ci:
    needs: [ci]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine docker tags and whether to push
        env:
          REF: ${{ github.ref }}
        run: |
          if [[ ${REF} == "refs/tags/"* ]]; then
            echo "DOCKER_DO_PUSH=true"
            version=$(git describe --exact-match --tags | sed 's/^v//')
            echo "DOCKER_TAGS=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG},${REGISTRY}/${IMAGE_NAME}:${version}"
          else
            echo "DOCKER_DO_PUSH=false"
            echo "DOCKER_TAGS=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          fi >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: extract-metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          push: ${{ env.DOCKER_DO_PUSH }}
          tags: ${{ env.DOCKER_TAGS }}
          labels: ${{ steps.extract-metadata.outputs.labels }}

      - name: Generate artifact attestation
        if: ${{ env.DOCKER_DO_PUSH == 'true' }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
